[package]
name = "hello"
version = "0.1.0"
authors = ["Robert Hanna <rdhanna@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies] # dependancies go here
rand = "0.6.5"
